# Generated by Django 4.1.5 on 2023-01-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order_by',
            field=models.CharField(choices=[('most viewed', 'most viewed'), ('date added', 'date added'), ('recently viewed', 'recently viewed'), ('shuffle', 'shuffle'), ('least viewed', 'least viewed')], default=None, max_length=32, null=True),
        ),
    ]
