# Generated by Django 4.1.6 on 2023-02-14 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_popular', models.DateTimeField(default=django.utils.timezone.now)),
                ('wikipedia_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(default='History', max_length=100)),
            ],
        ),
    ]
